tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "direnv"
brew "fish"
brew "fzf"
brew "graphviz"
brew "ruby"
brew "rustup"
brew "watch"

cask "docker"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
cask "spotify"
cask "typora"
cask "vlc"
cask "visual-studio-code"
